using SDL3;

namespace Sprout;

internal static class SdlUtils
{
    public static Key KeycodeToKey(SDL.Keycode code)
    {
        return code switch
        {
            SDL.Keycode.Return => Key.Return,
            SDL.Keycode.Escape => Key.Escape,
            SDL.Keycode.Backspace => Key.Backspace,
            SDL.Keycode.Tab => Key.Tab,
            SDL.Keycode.Space => Key.Space,
            SDL.Keycode.Hash => Key.Hash,
            SDL.Keycode.Apostrophe => Key.Apostrophe,
            SDL.Keycode.Comma => Key.Comma,
            SDL.Keycode.Minus => Key.Minus,
            SDL.Keycode.Period => Key.Period,
            SDL.Keycode.Slash => Key.ForwardSlash,
            SDL.Keycode.Alpha0 => Key.Num0,
            SDL.Keycode.Alpha1 => Key.Num1,
            SDL.Keycode.Alpha2 => Key.Num2,
            SDL.Keycode.Alpha3 => Key.Num3,
            SDL.Keycode.Alpha4 => Key.Num4,
            SDL.Keycode.Alpha5 => Key.Num5,
            SDL.Keycode.Alpha6 => Key.Num6,
            SDL.Keycode.Alpha7 => Key.Num7,
            SDL.Keycode.Alpha8 => Key.Num8,
            SDL.Keycode.Alpha9 => Key.Num9,
            SDL.Keycode.Semicolon => Key.Semicolon,
            SDL.Keycode.Equals => Key.Equals,
            SDL.Keycode.LeftBracket => Key.LeftBracket,
            SDL.Keycode.RightBracket => Key.RightBracket,
            SDL.Keycode.Backslash => Key.Backslash,
            SDL.Keycode.Grave => Key.Backquote,
            SDL.Keycode.A => Key.A,
            SDL.Keycode.B => Key.B,
            SDL.Keycode.C => Key.C,
            SDL.Keycode.D => Key.D,
            SDL.Keycode.E => Key.E,
            SDL.Keycode.F => Key.F,
            SDL.Keycode.G => Key.G,
            SDL.Keycode.H => Key.H,
            SDL.Keycode.I => Key.I,
            SDL.Keycode.J => Key.J,
            SDL.Keycode.K => Key.K,
            SDL.Keycode.L => Key.L,
            SDL.Keycode.M => Key.M,
            SDL.Keycode.N => Key.N,
            SDL.Keycode.O => Key.O,
            SDL.Keycode.P => Key.P,
            SDL.Keycode.Q => Key.Q,
            SDL.Keycode.R => Key.R,
            SDL.Keycode.S => Key.S,
            SDL.Keycode.T => Key.T,
            SDL.Keycode.U => Key.U,
            SDL.Keycode.V => Key.V,
            SDL.Keycode.W => Key.W,
            SDL.Keycode.X => Key.X,
            SDL.Keycode.Y => Key.Y,
            SDL.Keycode.Z => Key.Z,
            SDL.Keycode.Delete => Key.Delete,
            SDL.Keycode.Capslock => Key.CapsLock,
            SDL.Keycode.F1 => Key.F1,
            SDL.Keycode.F2 => Key.F2,
            SDL.Keycode.F3 => Key.F3,
            SDL.Keycode.F4 => Key.F4,
            SDL.Keycode.F5 => Key.F5,
            SDL.Keycode.F6 => Key.F6,
            SDL.Keycode.F7 => Key.F7,
            SDL.Keycode.F8 => Key.F8,
            SDL.Keycode.F9 => Key.F9,
            SDL.Keycode.F10 => Key.F10,
            SDL.Keycode.F11 => Key.F11,
            SDL.Keycode.F12 => Key.F12,
            SDL.Keycode.F13 => Key.F13,
            SDL.Keycode.F14 => Key.F14,
            SDL.Keycode.F15 => Key.F15,
            SDL.Keycode.F16 => Key.F16,
            SDL.Keycode.F17 => Key.F17,
            SDL.Keycode.F18 => Key.F18,
            SDL.Keycode.F19 => Key.F19,
            SDL.Keycode.F20 => Key.F20,
            SDL.Keycode.F21 => Key.F21,
            SDL.Keycode.F22 => Key.F22,
            SDL.Keycode.F23 => Key.F23,
            SDL.Keycode.F24 => Key.F24,
            SDL.Keycode.PrintScreen => Key.PrintScreen,
            SDL.Keycode.ScrollLock => Key.ScrollLock,
            SDL.Keycode.Pause => Key.Pause,
            SDL.Keycode.Insert => Key.Insert,
            SDL.Keycode.Home => Key.Home,
            SDL.Keycode.End => Key.End,
            SDL.Keycode.Pageup => Key.PageUp,
            SDL.Keycode.Pagedown => Key.PageDown,
            SDL.Keycode.Right => Key.Right,
            SDL.Keycode.Left => Key.Left,
            SDL.Keycode.Up => Key.Up,
            SDL.Keycode.Down => Key.Down,
            SDL.Keycode.NumLockClear => Key.NumLock,
            SDL.Keycode.KpDivide => Key.KeypadDivide,
            SDL.Keycode.KpMultiply => Key.KeypadMultiply,
            SDL.Keycode.KpMinus => Key.KeypadSubtract,
            SDL.Keycode.KpPlus => Key.KeypadAdd,
            SDL.Keycode.KpEnter => Key.KeypadEnter,
            SDL.Keycode.KpDecimal => Key.KeypadDecimal,
            SDL.Keycode.KpEquals => Key.KeypadEqual,
            SDL.Keycode.Kp0 => Key.Keypad0,
            SDL.Keycode.Kp1 => Key.Keypad1,
            SDL.Keycode.Kp2 => Key.Keypad2,
            SDL.Keycode.Kp3 => Key.Keypad3,
            SDL.Keycode.Kp4 => Key.Keypad4,
            SDL.Keycode.Kp5 => Key.Keypad5,
            SDL.Keycode.Kp6 => Key.Keypad6,
            SDL.Keycode.Kp7 => Key.Keypad7,
            SDL.Keycode.Kp8 => Key.Keypad8,
            SDL.Keycode.Kp9 => Key.Keypad9,
            SDL.Keycode.Menu => Key.Menu,
            SDL.Keycode.LCtrl => Key.LeftControl,
            SDL.Keycode.RCtrl => Key.RightControl,
            SDL.Keycode.LAlt => Key.LeftAlt,
            SDL.Keycode.RAlt => Key.RightAlt,
            SDL.Keycode.LShift => Key.LeftShift,
            SDL.Keycode.RShift => Key.RightShift,
            SDL.Keycode.LGUI => Key.LeftSuper,
            SDL.Keycode.RGUI => Key.RightSuper,
            _ => Key.Unknown
        };
    }

    /*public static MouseButton ButtonIndexToButton(byte button)
    {
        return (MouseButton) button;
    }*/
}