<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sprout.Audio\Sprout.Audio.csproj" />
    <ProjectReference Include="..\Sprout.Content\Sprout.Content.csproj" />
    <ProjectReference Include="..\Sprout.Graphics\Sprout.Graphics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="piko.SDL3" Version="0.0.5" />
  </ItemGroup>
</Project>
